version: '3.8'

networks:
  corp:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./
      cache_from:
        - zoom-manager-base-image:nx-base
      dockerfile: ./apps/api/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: zoom-manager-api:nx-dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: 'development'
      PORT: 4939
    networks:
      - corp
    restart: on-failure

  client:
    container_name: client
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/client/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: zoom-manager-client:nx-dev
    ports:
      - 4900:80
    environment:
      NODE_ENV: 'development'
      PORT: 4900
    networks:
      - corp
    restart: on-failure
