name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install required dependencies
        run: npm ci

      - name: Build Apps for Production
        run: npm run build:production

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: zoom-conference-manager
          heroku_email: logan.martlew@gmail.com
          appdir: dist/api
          procfile: web: node main.js
